---
- hosts: all
  become: true
  vars:
    localadmin: vagrant
  tasks:
  - name: Additional Software Packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - bash-completion
      - jq

  - name: kubeadm Completion in .bashrc
    lineinfile:
      path: "/home/{{ localadmin }}/.bashrc"
      regexp: ".*source.*kubeadm.completion.bash."
      line: "source <(kubeadm completion bash)"
      state: present

  - name: kubectl Completion in .bashrc
    lineinfile:
      path: "/home/{{ localadmin }}/.bashrc"
      regexp: ".*source.*kubectl.completion.bash."
      line: "source <(kubectl completion bash)"
      state: present

  - name: Color Prompt in .bashrc
    lineinfile:
      path: "/home/{{ localadmin }}/.bashrc"
      regexp: ".*force_color_prompt=.*"
      line: "force_color_prompt=yes"
      state: present
...
